development:
  bucket: photoomni.dev
  access_key_id: AKIAJXFF6RBMRIJECXYA
  secret_access_key: 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

production:
  bucket: photoomni.prod
  access_key_id: AKIAJXFF6RBMRIJECXYA
  secret_access_key: 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

